### ISSUE TITLE
Elaborar questionário para clientes em potencial.

### ISSUE THREAD

**Issue by Victor-Oliveira** [devfest-ufrn/SmartFome#1]
Elaborar questionários sobre os hábitos do cliente/consumidor de comida de rua.
- Informações pessoais.
- Refeições.
- Frequência de consumo de comida de rua.
- Etc.

**Comment by clahzita** [comment]
[https://drive.google.com/open?id=124v4Mst_ZCV7eN1Y4yU22pQlqm-kmB0DYICcxWgBiv4](url)
