### ISSUE TITLE
API Maps

### ISSUE THREAD

**Issue by clahzita** [devfest-ufrn/SmartFome#14]
Aprender a usar para implementar no perfil do vendedor

**Comment by clahzita** [comment]
[https://developers.google.com/maps/documentation/javascript/tutorial?hl=pt-br](url)
Guia

**Comment by sboliveira** [comment]
https://developers.google.com/maps/?hl=pt-br
o outro tava quebrado.

**Comment by Victor-Oliveira** [comment]
Demos os primeiros passos no estudo da API e decidimos usar mesmo a do Google.
