### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by clahzita** [devfest-ufrn/SmartFome#7]
- [x] Casos de Uso

- [x] Diagrama de classe para Banco de Dados

**Comment by Victor-Oliveira** [comment]
Casos de uso:
https://docs.google.com/document/d/1WeC38xL62t4Q45YErdvTYVn8mQb5cDrOAPT54oyYk7M/edit?usp=sharing

**Comment by Victor-Oliveira** [comment]
Diagrama de classes: #11 
![smartfome-cd](https://user-images.githubusercontent.com/4496309/31677523-6974981a-b341-11e7-8379-2fe00e1801f7.png)
